ls:
  .ts: kebab-case
  .js: kebab-case
  .d.ts: kebab-case

ignore:
  - '**/node_modules'
  - '**/dist'
  - '**/*.config.{js,mjs,cjs,ts,cts,mts}'
  - '**/*.test.{js,mjs,cjs,ts,cts,mts}'
  - .git
  - .github
  - .vscode
  - .pnpm
  - crates
  - temp
  - tmp
  - target
  - 'crates/rn/tests/fixtures/**/_test.js' # `_test.js` is a special file, which will be treat as the entry file while executing the build output of fixture.
  - packages/rn/npm
  - 'packages/rn/tests/fixtures/**/_config.ts'
  # FIXME: should not ignore following folders
  - apps
